version: "3.9"

services:
  api1: &api
    build: .
    hostname: api01
    ports:
      - "8081:8080"
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_SECRET=${DB_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"

  api2:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "270MB"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: rinhabackend
